/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedRunIndexRouteImport } from './routes/_authenticated/run/index'
import { Route as AuthenticatedResearchIndexRouteImport } from './routes/_authenticated/research/index'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents.index'
import { Route as AuthenticatedRunTemplateIdRouteImport } from './routes/_authenticated/run/$templateId'
import { Route as AuthenticatedHistoryRunIdRouteImport } from './routes/_authenticated/history/$runId'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat/$threadId'
import { Route as AuthenticatedAgentsManageRouteImport } from './routes/_authenticated/agents.manage'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin/usage'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated/admin/knowledge'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAgentsManageRunsRouteImport } from './routes/_authenticated/agents.manage.runs'
import { Route as AuthenticatedAgentsManageProvidersRouteImport } from './routes/_authenticated/agents.manage.providers'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunIndexRoute = AuthenticatedRunIndexRouteImport.update({
  id: '/run/',
  path: '/run/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResearchIndexRoute =
  AuthenticatedResearchIndexRouteImport.update({
    id: '/research/',
    path: '/research/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const AuthenticatedRunTemplateIdRoute =
  AuthenticatedRunTemplateIdRouteImport.update({
    id: '/run/$templateId',
    path: '/run/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRunIdRoute =
  AuthenticatedHistoryRunIdRouteImport.update({
    id: '/history/$runId',
    path: '/history/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsManageRoute =
  AuthenticatedAgentsManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/admin/templates',
    path: '/admin/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/admin/knowledge',
    path: '/admin/knowledge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsManageRunsRoute =
  AuthenticatedAgentsManageRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedAgentsManageRoute,
  } as any)
const AuthenticatedAgentsManageProvidersRoute =
  AuthenticatedAgentsManageProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAgentsManageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/governance': typeof AuthenticatedGovernanceRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/agents/manage': typeof AuthenticatedAgentsManageRouteWithChildren
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/history/$runId': typeof AuthenticatedHistoryRunIdRoute
  '/run/$templateId': typeof AuthenticatedRunTemplateIdRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/research/': typeof AuthenticatedResearchIndexRoute
  '/run/': typeof AuthenticatedRunIndexRoute
  '/agents/manage/providers': typeof AuthenticatedAgentsManageProvidersRoute
  '/agents/manage/runs': typeof AuthenticatedAgentsManageRunsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/verify/$id': typeof VerifyIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/agents/manage': typeof AuthenticatedAgentsManageRouteWithChildren
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/history/$runId': typeof AuthenticatedHistoryRunIdRoute
  '/run/$templateId': typeof AuthenticatedRunTemplateIdRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/research': typeof AuthenticatedResearchIndexRoute
  '/run': typeof AuthenticatedRunIndexRoute
  '/agents/manage/providers': typeof AuthenticatedAgentsManageProvidersRoute
  '/agents/manage/runs': typeof AuthenticatedAgentsManageRunsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/verify/$id': typeof VerifyIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/agents/manage': typeof AuthenticatedAgentsManageRouteWithChildren
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/history/$runId': typeof AuthenticatedHistoryRunIdRoute
  '/_authenticated/run/$templateId': typeof AuthenticatedRunTemplateIdRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/research/': typeof AuthenticatedResearchIndexRoute
  '/_authenticated/run/': typeof AuthenticatedRunIndexRoute
  '/_authenticated/agents/manage/providers': typeof AuthenticatedAgentsManageProvidersRoute
  '/_authenticated/agents/manage/runs': typeof AuthenticatedAgentsManageRunsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/agents'
    | '/governance'
    | '/integrations'
    | '/settings'
    | '/templates'
    | '/verify/$id'
    | '/admin/dashboard'
    | '/admin/knowledge'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/usage'
    | '/agents/manage'
    | '/chat/$threadId'
    | '/history/$runId'
    | '/run/$templateId'
    | '/agents/'
    | '/chat/'
    | '/history/'
    | '/research/'
    | '/run/'
    | '/agents/manage/providers'
    | '/agents/manage/runs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/governance'
    | '/integrations'
    | '/settings'
    | '/templates'
    | '/verify/$id'
    | '/'
    | '/admin/dashboard'
    | '/admin/knowledge'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/usage'
    | '/agents/manage'
    | '/chat/$threadId'
    | '/history/$runId'
    | '/run/$templateId'
    | '/agents'
    | '/chat'
    | '/history'
    | '/research'
    | '/run'
    | '/agents/manage/providers'
    | '/agents/manage/runs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/agents'
    | '/_authenticated/governance'
    | '/_authenticated/integrations'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/verify/$id'
    | '/_authenticated/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/usage'
    | '/_authenticated/agents/manage'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/history/$runId'
    | '/_authenticated/run/$templateId'
    | '/_authenticated/agents/'
    | '/_authenticated/chat/'
    | '/_authenticated/history/'
    | '/_authenticated/research/'
    | '/_authenticated/run/'
    | '/_authenticated/agents/manage/providers'
    | '/_authenticated/agents/manage/runs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/run/': {
      id: '/_authenticated/run/'
      path: '/run'
      fullPath: '/run/'
      preLoaderRoute: typeof AuthenticatedRunIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/': {
      id: '/_authenticated/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof AuthenticatedResearchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/run/$templateId': {
      id: '/_authenticated/run/$templateId'
      path: '/run/$templateId'
      fullPath: '/run/$templateId'
      preLoaderRoute: typeof AuthenticatedRunTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/$runId': {
      id: '/_authenticated/history/$runId'
      path: '/history/$runId'
      fullPath: '/history/$runId'
      preLoaderRoute: typeof AuthenticatedHistoryRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/manage': {
      id: '/_authenticated/agents/manage'
      path: '/manage'
      fullPath: '/agents/manage'
      preLoaderRoute: typeof AuthenticatedAgentsManageRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/admin/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/manage/runs': {
      id: '/_authenticated/agents/manage/runs'
      path: '/runs'
      fullPath: '/agents/manage/runs'
      preLoaderRoute: typeof AuthenticatedAgentsManageRunsRouteImport
      parentRoute: typeof AuthenticatedAgentsManageRoute
    }
    '/_authenticated/agents/manage/providers': {
      id: '/_authenticated/agents/manage/providers'
      path: '/providers'
      fullPath: '/agents/manage/providers'
      preLoaderRoute: typeof AuthenticatedAgentsManageProvidersRouteImport
      parentRoute: typeof AuthenticatedAgentsManageRoute
    }
  }
}

interface AuthenticatedAgentsManageRouteChildren {
  AuthenticatedAgentsManageProvidersRoute: typeof AuthenticatedAgentsManageProvidersRoute
  AuthenticatedAgentsManageRunsRoute: typeof AuthenticatedAgentsManageRunsRoute
}

const AuthenticatedAgentsManageRouteChildren: AuthenticatedAgentsManageRouteChildren =
  {
    AuthenticatedAgentsManageProvidersRoute:
      AuthenticatedAgentsManageProvidersRoute,
    AuthenticatedAgentsManageRunsRoute: AuthenticatedAgentsManageRunsRoute,
  }

const AuthenticatedAgentsManageRouteWithChildren =
  AuthenticatedAgentsManageRoute._addFileChildren(
    AuthenticatedAgentsManageRouteChildren,
  )

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsManageRoute: typeof AuthenticatedAgentsManageRouteWithChildren
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsManageRoute: AuthenticatedAgentsManageRouteWithChildren,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedHistoryRunIdRoute: typeof AuthenticatedHistoryRunIdRoute
  AuthenticatedRunTemplateIdRoute: typeof AuthenticatedRunTemplateIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
  AuthenticatedResearchIndexRoute: typeof AuthenticatedResearchIndexRoute
  AuthenticatedRunIndexRoute: typeof AuthenticatedRunIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminKnowledgeRoute: AuthenticatedAdminKnowledgeRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedHistoryRunIdRoute: AuthenticatedHistoryRunIdRoute,
  AuthenticatedRunTemplateIdRoute: AuthenticatedRunTemplateIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  AuthenticatedResearchIndexRoute: AuthenticatedResearchIndexRoute,
  AuthenticatedRunIndexRoute: AuthenticatedRunIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
